# Generated by Django 2.2.11 on 2020-03-31 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaflet_storage', '0004_tilelayer_tms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='tilelayer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maps', to='leaflet_storage.TileLayer', verbose_name='background'),
        ),
    ]
